-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 09:57:55 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema world
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema world
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `world` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`instituicoes_ensino_superior`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituicoes_ensino_superior` (
  `ies_id` INT NOT NULL,
  `sigla_ies` VARCHAR(20) NOT NULL,
  `nome_ies` VARCHAR(100) NOT NULL,
  `instituicoes_ensino_superiorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`ies_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8
COMMENT = 'Relação das Insttuições de Ensino Superior (IES)';


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `estado_id` INT NOT NULL,
  `sigla_estado` VARCHAR(2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidades` (
  `cidade_id` INT NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estados_estado_id` INT NOT NULL,
  PRIMARY KEY (`cidade_id`, `estados_estado_id`),
  INDEX `fk_cidades_estados_idx` (`estados_estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cidades_estados`
    FOREIGN KEY (`estados_estado_id`)
    REFERENCES `mydb`.`estados` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`enderecos_ies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`enderecos_ies` (
  `endereco_id` INT NOT NULL,
  `logradouro` VARCHAR(150) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(10,8) NOT NULL,
  `cidades_cidade_id` INT NOT NULL,
  `cidades_estados_estado_id` INT NOT NULL,
  `instituicoes_ensino_superior_ies_id` INT NOT NULL,
  PRIMARY KEY (`endereco_id`, `cidades_cidade_id`, `cidades_estados_estado_id`, `instituicoes_ensino_superior_ies_id`),
  INDEX `fk_enderecos_ies_cidades1_idx` (`cidades_cidade_id` ASC, `cidades_estados_estado_id` ASC) VISIBLE,
  INDEX `fk_enderecos_ies_instituicoes_ensino_superior1_idx` (`instituicoes_ensino_superior_ies_id` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_ies_cidades1`
    FOREIGN KEY (`cidades_cidade_id` , `cidades_estados_estado_id`)
    REFERENCES `mydb`.`cidades` (`cidade_id` , `estados_estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enderecos_ies_instituicoes_ensino_superior1`
    FOREIGN KEY (`instituicoes_ensino_superior_ies_id`)
    REFERENCES `mydb`.`instituicoes_ensino_superior` (`ies_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status_juridico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`status_juridico` (
  `status_juridico_id` INT NOT NULL,
  `status_juridico` VARCHAR(15) NOT NULL COMMENT 'Privado, Estadual, Federal',
  `instituicoes_ensino_superior_ies_id` INT NOT NULL,
  PRIMARY KEY (`status_juridico_id`, `instituicoes_ensino_superior_ies_id`),
  INDEX `fk_status_juridico_instituicoes_ensino_superior1_idx` (`instituicoes_ensino_superior_ies_id` ASC) VISIBLE,
  CONSTRAINT `fk_status_juridico_instituicoes_ensino_superior1`
    FOREIGN KEY (`instituicoes_ensino_superior_ies_id`)
    REFERENCES `mydb`.`instituicoes_ensino_superior` (`ies_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modalidades_pos_graduacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modalidades_pos_graduacao` (
  `modalide_id` INT NOT NULL,
  `modalidade_pos_graduacao` VARCHAR(45) NOT NULL COMMENT 'Especialização, mestrado lato sensu, mestrado stricto sensu, doutorado stricto sensu, mestrado profissional',
  `instituicoes_ensino_superior_ies_id` INT NOT NULL,
  PRIMARY KEY (`modalide_id`, `instituicoes_ensino_superior_ies_id`),
  INDEX `fk_modalidades_pos_graduacao_instituicoes_ensino_superior1_idx` (`instituicoes_ensino_superior_ies_id` ASC) VISIBLE,
  CONSTRAINT `fk_modalidades_pos_graduacao_instituicoes_ensino_superior1`
    FOREIGN KEY (`instituicoes_ensino_superior_ies_id`)
    REFERENCES `mydb`.`instituicoes_ensino_superior` (`ies_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grandes_areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grandes_areas` (
  `grande_area_id` INT NOT NULL,
  `grande_area` VARCHAR(30) NULL,
  `instituicoes_ensino_superior_ies_id` INT NOT NULL,
  PRIMARY KEY (`grande_area_id`, `instituicoes_ensino_superior_ies_id`),
  INDEX `fk_grandes_areas_instituicoes_ensino_superior1_idx` (`instituicoes_ensino_superior_ies_id` ASC) VISIBLE,
  CONSTRAINT `fk_grandes_areas_instituicoes_ensino_superior1`
    FOREIGN KEY (`instituicoes_ensino_superior_ies_id`)
    REFERENCES `mydb`.`instituicoes_ensino_superior` (`ies_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`areas_conhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`areas_conhecimento` (
  `area_conhecimento_id` INT NOT NULL,
  `area_conhecimento` VARCHAR(70) NOT NULL,
  `grandes_areas_grande_area_id` INT NOT NULL,
  PRIMARY KEY (`area_conhecimento_id`, `grandes_areas_grande_area_id`),
  INDEX `fk_areas_conhecimento_grandes_areas1_idx` (`grandes_areas_grande_area_id` ASC) VISIBLE,
  CONSTRAINT `fk_areas_conhecimento_grandes_areas1`
    FOREIGN KEY (`grandes_areas_grande_area_id`)
    REFERENCES `mydb`.`grandes_areas` (`grande_area_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`areas_pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`areas_pesquisa` (
  `area_pesquisa_id` INT NOT NULL,
  `area_pesquisa` VARCHAR(120) NOT NULL,
  `areas_conhecimento_area_conhecimento_id` INT NOT NULL,
  PRIMARY KEY (`area_pesquisa_id`, `areas_conhecimento_area_conhecimento_id`),
  INDEX `fk_areas_pesquisa_areas_conhecimento1_idx` (`areas_conhecimento_area_conhecimento_id` ASC) VISIBLE,
  CONSTRAINT `fk_areas_pesquisa_areas_conhecimento1`
    FOREIGN KEY (`areas_conhecimento_area_conhecimento_id`)
    REFERENCES `mydb`.`areas_conhecimento` (`area_conhecimento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`temas_especificos_pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`temas_especificos_pesquisa` (
  `temas_pesquisa_id` INT NOT NULL,
  `tema_pesquisa` VARCHAR(100) NULL,
  `areas_pesquisa_area_pesquisa_id` INT NOT NULL,
  PRIMARY KEY (`temas_pesquisa_id`, `areas_pesquisa_area_pesquisa_id`),
  INDEX `fk_temas_especificos_pesquisa_areas_pesquisa1_idx` (`areas_pesquisa_area_pesquisa_id` ASC) VISIBLE,
  CONSTRAINT `fk_temas_especificos_pesquisa_areas_pesquisa1`
    FOREIGN KEY (`areas_pesquisa_area_pesquisa_id`)
    REFERENCES `mydb`.`areas_pesquisa` (`area_pesquisa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `world` ;

-- -----------------------------------------------------
-- Table `world`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`country` (
  `Code` CHAR(3) NOT NULL DEFAULT '',
  `Name` CHAR(52) NOT NULL DEFAULT '',
  `Continent` ENUM('Asia', 'Europe', 'North America', 'Africa', 'Oceania', 'Antarctica', 'South America') NOT NULL DEFAULT 'Asia',
  `Region` CHAR(26) NOT NULL DEFAULT '',
  `SurfaceArea` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `IndepYear` SMALLINT NULL DEFAULT NULL,
  `Population` INT NOT NULL DEFAULT '0',
  `LifeExpectancy` DECIMAL(3,1) NULL DEFAULT NULL,
  `GNP` DECIMAL(10,2) NULL DEFAULT NULL,
  `GNPOld` DECIMAL(10,2) NULL DEFAULT NULL,
  `LocalName` CHAR(45) NOT NULL DEFAULT '',
  `GovernmentForm` CHAR(45) NOT NULL DEFAULT '',
  `HeadOfState` CHAR(60) NULL DEFAULT NULL,
  `Capital` INT NULL DEFAULT NULL,
  `Code2` CHAR(2) NOT NULL DEFAULT '',
  PRIMARY KEY (`Code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `world`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`city` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` CHAR(35) NOT NULL DEFAULT '',
  `CountryCode` CHAR(3) NOT NULL DEFAULT '',
  `District` CHAR(20) NOT NULL DEFAULT '',
  `Population` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  INDEX `CountryCode` (`CountryCode` ASC) VISIBLE,
  CONSTRAINT `city_ibfk_1`
    FOREIGN KEY (`CountryCode`)
    REFERENCES `world`.`country` (`Code`))
ENGINE = InnoDB
AUTO_INCREMENT = 4080
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `world`.`countrylanguage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `world`.`countrylanguage` (
  `CountryCode` CHAR(3) NOT NULL DEFAULT '',
  `Language` CHAR(30) NOT NULL DEFAULT '',
  `IsOfficial` ENUM('T', 'F') NOT NULL DEFAULT 'F',
  `Percentage` DECIMAL(4,1) NOT NULL DEFAULT '0.0',
  PRIMARY KEY (`CountryCode`, `Language`),
  INDEX `CountryCode` (`CountryCode` ASC) VISIBLE,
  CONSTRAINT `countryLanguage_ibfk_1`
    FOREIGN KEY (`CountryCode`)
    REFERENCES `world`.`country` (`Code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
